# Generated by Django 5.0.4 on 2024-04-18 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtdelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='CoffeeUsers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('birth_day', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, null=True, unique=True, verbose_name='Рабочая почта')),
                ('position', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Должность')),
                ('avatar', models.ImageField(blank=True, default='ava/default.jpg', null=True, upload_to='avatar/', verbose_name='Фото профиля')),
                ('nachalnik', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Админ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='SuperMega')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='Логин')),
                ('telegram_code', models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Код')),
                ('code_creation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('chat_id', models.CharField(max_length=150, null=True, unique=True, verbose_name='ID Телеграмм')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('otdel', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.otdelclass', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
